// Quotations reuse the authenticated panel and the same panel_entities database.
let QUOTES=[],QUOTE=null,quoteTimer=null,quoteDirty=false,quoteSaving=false;
const qel=id=>document.getElementById(id);
const qEsc=x=>esc(x);
const qMoney=x=>Number(x).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function qNum(x){let s=String(x??'').trim().replace(/\s|R\$/g,'');if(!s)return NaN;if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');return Number(s)}
const qItemKey=x=>x.sc+'|'+x.item;
const qDefaultSupplier=()=>({name:'',email:'',freightType:'CIF',freight:'',ipi:'',extra:'',payment:'',delivery:'',notes:''});
function qEvent(action,detail){QUOTE.events??=[];QUOTE.events.push({action,detail:detail||'',at:new Date().toISOString(),by:ACTIVE_USER})}
async function qRequest(method,body){const r=await fetch('/api/quotes',{method,headers:authHeaders({'Content-Type':'application/json'}),body:body?JSON.stringify(body):undefined,cache:'no-store'});const x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.error||'Erro ao acessar cotações');return x}
async function loadQuotes(){try{const response=await qRequest('GET');QUOTES=response.quotes||[];renderQuoteList();qel('q-sync').textContent='Processos disponíveis para a equipe';if(QUOTE&&!quoteDirty){const latest=QUOTES.find(x=>x.id===QUOTE.id);if(latest&&latest._serverVersion!==QUOTE._serverVersion){QUOTE=structuredClone(latest);renderQuote()}}}catch(e){qel('q-sync').textContent=e.message}}
function renderQuoteList(){qel('q-list').innerHTML=QUOTES.length?QUOTES.slice().sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt))).map(x=>`<button class="quote-list-item" type="button" onclick="openQuote('${qEsc(x.id)}')"><strong>${qEsc([...new Set(x.items.map(i=>i.sc))].join(' · '))}</strong><small>${qEsc(x.company)} · ${qEsc(x.status)} · ${qEsc(x.updatedAt?.slice(0,10)||'')}</small></button>`).join(''):'<p class="quote-muted">Ainda não há processos salvos. Selecione itens da Pharmabag e crie o primeiro.</p>'}
function openQuote(id){if(quoteDirty&&!confirm('Há alterações ainda não salvas. Abrir outro processo?'))return;const x=QUOTES.find(y=>y.id===id);if(!x)return;QUOTE=structuredClone(x);quoteDirty=false;renderQuote()}
function createQuote(){const indices=selectedIndexes(),rows=indices.map(i=>DATA[i]).filter(x=>x.empresa==='Pharmabag');if(!rows.length){toast('Marque os itens na aba Pharmabag ou na listagem antes de criar a cotação.','err',5500);return}if(rows.length!==indices.length){toast('Selecione somente itens da Pharmabag neste piloto.','err');return}if(quoteDirty&&!confirm('Há alterações ainda não salvas. Criar novo processo?'))return;QUOTE={id:'COT-'+(crypto.randomUUID?crypto.randomUUID():String(Date.now())+'-draft'),company:'Pharmabag',status:'Em preparação',createdAt:new Date().toISOString(),createdBy:ACTIVE_USER,updatedAt:new Date().toISOString(),items:rows.map(x=>({sc:String(x.sc),item:String(x.item),code:String(x.codigoProduto||''),description:String(x.descricao||''),quantity:String(x.quantidade||''),unit:String(x.um||'')})),suppliers:Array.from({length:5},qDefaultSupplier),lastPrices:{},prices:{},itemNotes:{},deadline:'',deliveryAddress:'Rua Campinas, 1116 · Vila Carvalho · Ribeirão Preto/SP · CEP 14075-070',deliveryHours:'Das 08:30 às 11:30 e das 13:30 às 16:00',extraInfo:'Informe preço unitário, IPI, prazo de entrega, frete, condição de pagamento e validade da proposta.',buyer:ACTIVE_USER,chosenSupplier:'',choiceReason:'',pcNumber:'',events:[]};qEvent('processo_criado',QUOTE.items.map(x=>qItemKey(x)).join(', '));quoteDirty=true;renderQuote();scheduleQuoteSave()}
function qField(k,val){if(!QUOTE)return;QUOTE[k]=val;quoteChanged();if(['deadline','deliveryAddress','deliveryHours','extraInfo','buyer'].includes(k))renderQuoteEmail()}
function qItem(i,k,val){QUOTE.items[i][k]=val;quoteChanged();renderQuoteEmail();renderMapBody()}
function qSupplier(i,k,val){QUOTE.suppliers[i][k]=val;if(k==='freightType')renderSuppliers();quoteChanged();renderMapTotals();if(k==='name')renderChosenSupplier()}
function qPrice(key,i,val){QUOTE.prices[key]??=Array(5).fill('');QUOTE.prices[key][i]=val;quoteChanged();renderMapTotals()}
function quoteChanged(){if(QUOTE.status==='Finalizado'){QUOTE.status='Em preparação';QUOTE.finishedAt=null}QUOTE.updatedAt=new Date().toISOString();quoteDirty=true;qel('q-save-status').textContent='Salvando…';scheduleQuoteSave()}
function scheduleQuoteSave(){clearTimeout(quoteTimer);quoteTimer=setTimeout(saveQuote,2200)}
async function saveQuote(){if(!QUOTE||!quoteDirty||quoteSaving)return;quoteSaving=true;const snapshot=structuredClone(QUOTE);try{const saved=await qRequest('POST',{quote:snapshot,expectedRevision:snapshot._serverVersion||0});if(QUOTE.id!==snapshot.id)return;QUOTE._serverVersion=saved.revision;const idx=QUOTES.findIndex(x=>x.id===QUOTE.id);if(idx<0)QUOTES.unshift(structuredClone(QUOTE));else QUOTES[idx]=structuredClone(QUOTE);renderQuoteList();if(QUOTE.updatedAt===snapshot.updatedAt){quoteDirty=false;qel('q-save-status').textContent='Salvo na base · '+new Date().toLocaleTimeString('pt-BR')}else scheduleQuoteSave()}catch(e){qel('q-save-status').textContent='Não salvo: '+e.message;toast('Cotação pendente de salvamento. '+e.message,'err',6000)}finally{quoteSaving=false;if(quoteDirty&&QUOTE?.updatedAt!==snapshot.updatedAt)scheduleQuoteSave()}}
function renderQuote(){if(!QUOTE){qel('q-editor').hidden=true;qel('q-empty').hidden=false;return}qel('q-empty').hidden=true;qel('q-editor').hidden=false;qel('q-process').textContent='Processo · SC '+[...new Set(QUOTE.items.map(x=>x.sc))].join(' · ');qel('q-save-status').textContent=QUOTE._serverVersion?'Salvo na base':'Novo processo';const fields=['deadline','deliveryAddress','deliveryHours','extraInfo','buyer','pcNumber','choiceReason'];for(const f of fields)qel('q-'+f).value=QUOTE[f]||'';qel('q-items').innerHTML=QUOTE.items.map((x,i)=>`<tr><td>${qEsc(x.sc)}</td><td>${qEsc(x.item)}</td><td>${qEsc(x.code)}</td><td><textarea aria-label="Descrição" oninput="qItem(${i},'description',this.value)">${qEsc(x.description)}</textarea></td><td><input aria-label="Quantidade" value="${qEsc(x.quantity)}" oninput="qItem(${i},'quantity',this.value)"></td><td><input aria-label="UM" value="${qEsc(x.unit)}" oninput="qItem(${i},'unit',this.value)"></td></tr>`).join('');renderSuppliers();renderChosenSupplier();renderQuoteEmail();renderMapBody()}
function renderSuppliers(){qel('q-suppliers').innerHTML=QUOTE.suppliers.map((s,i)=>`<div class="quote-supplier"><strong>Fornecedor ${i+1}</strong><label>Nome<input value="${qEsc(s.name)}" oninput="qSupplier(${i},'name',this.value)"></label><label>E-mail<input type="email" value="${qEsc(s.email)}" oninput="qSupplier(${i},'email',this.value)"></label><label>Pagamento<input value="${qEsc(s.payment)}" oninput="qSupplier(${i},'payment',this.value)"></label><label>Frete<select onchange="qSupplier(${i},'freightType',this.value)"><option ${s.freightType==='CIF'?'selected':''}>CIF</option><option ${s.freightType==='FOB'?'selected':''}>FOB</option></select></label><label>Frete FOB R$<input ${s.freightType==='FOB'?'':'disabled'} value="${qEsc(s.freight)}" oninput="qSupplier(${i},'freight',this.value)"></label><label>IPI adicional R$<input value="${qEsc(s.ipi)}" oninput="qSupplier(${i},'ipi',this.value)"></label><label>Outras despesas R$<input value="${qEsc(s.extra)}" oninput="qSupplier(${i},'extra',this.value)"></label><label>Entrega<input value="${qEsc(s.delivery)}" oninput="qSupplier(${i},'delivery',this.value)"></label><label>Observações<input value="${qEsc(s.notes)}" oninput="qSupplier(${i},'notes',this.value)"></label></div>`).join('')}
function renderChosenSupplier(){qel('q-chosenSupplier').innerHTML='<option value="">A definir</option>'+QUOTE.suppliers.map((s,i)=>`<option value="${i}" ${String(QUOTE.chosenSupplier)===String(i)?'selected':''}>${qEsc(s.name||'Fornecedor '+(i+1))}</option>`).join('')}
function qScList(){return [...new Set(QUOTE.items.map(x=>x.sc))].join(' · ')}
function quoteEmailHtml(){const rows=QUOTE.items.map(x=>`<tr><td>${qEsc(x.code||'—')}</td><td>${qEsc(x.sc)} / ${qEsc(x.item)}</td><td>${qEsc(x.description)}</td><td style="text-align:right">${qEsc(x.quantity)} ${qEsc(x.unit)}</td></tr>`).join('');const date=QUOTE.deadline?new Date(QUOTE.deadline).toLocaleString('pt-BR'):'[definir prazo]';return `<div style="font:13px Arial,sans-serif;color:#253b50;max-width:760px"><table width="100%" style="border-top:5px solid #5687b8"><tr><td><img src="${location.origin}/assets/pharmabag-logo.jpg" width="155" alt="Pharmabag" style="width:155px;height:auto"></td><td style="text-align:right;color:#193855"><strong>SOLICITAÇÃO DE COTAÇÃO</strong><br>SC ${qEsc(qScList())}</td></tr></table><div style="background:#edf4fa;padding:12px;line-height:1.6"><strong>Pharmabag Indústria e Comércio de Produtos Médicos Ltda</strong><br>CNPJ 08.299.707/0001-52 · IE 582.717.761.110<br>Rua Campinas, 1116 · Vila Carvalho · Ribeirão Preto/SP · CEP 14075-070<br>aline.lima@pharmabag.com.br · (11) 3041-4600 ramal 1001 · (11) 99942-3462</div><p>Olá, Prezados,</p><p>Solicitamos sua proposta comercial para os itens abaixo.<br>Por gentileza, envie sua cotação até <strong>${qEsc(date)}</strong>.</p><table width="100%" cellspacing="0" style="border-collapse:collapse"><tr style="background:#dcebf7;color:#193855"><th style="padding:8px;text-align:left">Código</th><th style="padding:8px;text-align:left">SC / item</th><th style="padding:8px;text-align:left">Descrição</th><th style="padding:8px;text-align:right">Quantidade</th></tr>${rows.replace(/<td>/g,'<td style="border-bottom:1px solid #dce6ee;padding:7px">')}</table><p><strong>Entrega:</strong> ${qEsc(QUOTE.deliveryAddress)}<br><strong>Horário:</strong> ${qEsc(QUOTE.deliveryHours)}</p><p>${qEsc(QUOTE.extraInfo).replace(/\n/g,'<br>')}</p><p>Desde já, agradeço a atenção e fico no aguardo do retorno.</p><p>Obrigada,<br><strong>${qEsc(QUOTE.buyer||'Aline Lima')}</strong><br>Compras | Pharmabag</p><p style="font-size:11px;color:#63768a">Esta solicitação de cotação não constitui pedido de compra.</p></div>`}
function renderQuoteEmail(){qel('q-subject').textContent='Cotação | Pharmabag | SC '+qScList();qel('q-email').innerHTML=quoteEmailHtml()}
async function copyQuote(){if(!QUOTE.deadline)return toast('Defina o prazo de resposta antes de copiar.','err');const html=quoteEmailHtml(),plain=qel('q-email').innerText;try{await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([plain],{type:'text/plain'})})]);toast('Cotação copiada. Revise o e-mail antes de enviar.')}catch(e){const r=document.createRange();r.selectNodeContents(qel('q-email'));const selection=getSelection();selection.removeAllRanges();selection.addRange(r);document.execCommand('copy');selection.removeAllRanges();toast('Cotação copiada; confira a formatação no Outlook.')}}
async function copyQuoteSubject(){try{await navigator.clipboard.writeText(qel('q-subject').textContent);toast('Assunto copiado.')}catch(e){toast('Selecione e copie o assunto exibido.','err')}}
function renderMapBody(){qel('q-map-items').innerHTML=QUOTE.items.map(x=>{let key=qItemKey(x);return `<tr><td><input value="${qEsc(QUOTE.lastPrices[key]||'')}" oninput="QUOTE.lastPrices['${qEsc(key)}']=this.value;quoteChanged()"></td><td>${qEsc(x.sc)} / ${qEsc(x.item)}</td><td>${qEsc(x.description)}</td><td>${qEsc(x.quantity)} ${qEsc(x.unit)}</td>${QUOTE.suppliers.map((_,i)=>`<td><input aria-label="Preço unitário fornecedor ${i+1}" value="${qEsc((QUOTE.prices[key]||[])[i]||'')}" oninput="qPrice('${qEsc(key)}',${i},this.value)"><small class="q-item-total" data-item="${qEsc(key)}" data-supplier="${i}">—</small></td>`).join('')}<td><input value="${qEsc(QUOTE.itemNotes[key]||'')}" oninput="QUOTE.itemNotes['${qEsc(key)}']=this.value;quoteChanged()"></td></tr>`}).join('');renderMapTotals()}
function quoteTotals(){return QUOTE.suppliers.map((s,i)=>{let sum=0,count=0;QUOTE.items.forEach(x=>{let p=qNum((QUOTE.prices[qItemKey(x)]||[])[i]),q=qNum(x.quantity);if(Number.isFinite(p)&&p>=0&&Number.isFinite(q)&&q>0){sum+=p*q;count++}});let freight=s.freightType==='FOB'?qNum(s.freight):0,ipi=qNum(s.ipi),extra=qNum(s.extra);return {sum,count,final:count===QUOTE.items.length&&[freight,ipi,extra].every(n=>Number.isFinite(n)&&n>=0)?sum+freight+ipi+extra:null}})}
function renderMapTotals(){let totals=quoteTotals();qel('q-totals').innerHTML=totals.map((t,i)=>`<div><strong>${qEsc(QUOTE.suppliers[i].name||'Fornecedor '+(i+1))}</strong><br>Itens: ${qMoney(t.sum)} · ${t.count}/${QUOTE.items.length}<br><strong>Total com despesas: ${t.final===null?'Pendente':qMoney(t.final)}</strong></div>`).join('');document.querySelectorAll('.q-item-total').forEach(el=>{const x=QUOTE.items.find(y=>qItemKey(y)===el.dataset.item),p=qNum((QUOTE.prices[el.dataset.item]||[])[+el.dataset.supplier]),q=qNum(x?.quantity);el.textContent=Number.isFinite(p)&&Number.isFinite(q)?qMoney(p*q):'—'})}
function printQuote(mode){if(!QUOTE)return;const sums=quoteTotals(),names=QUOTE.suppliers.map((s,i)=>qEsc(s.name||'Fornecedor '+(i+1)));const items=QUOTE.items.map(x=>{let key=qItemKey(x),q=qNum(x.quantity);return `<tr><td>${qEsc(QUOTE.lastPrices[key]||'—')}</td><td>${qEsc(x.sc)} / ${qEsc(x.item)}</td><td>${qEsc(x.description)}</td><td>${qEsc(x.quantity)} ${qEsc(x.unit)}</td>${QUOTE.suppliers.map((s,i)=>{let p=qNum((QUOTE.prices[key]||[])[i]);return `<td>${Number.isFinite(p)?qMoney(p)+' / '+qMoney(p*q):'—'}</td>`}).join('')}<td>${qEsc(QUOTE.itemNotes[key]||'')}</td></tr>`}).join('');const terms=[['Subtotal',(_,i)=>qMoney(sums[i].sum)],['IPI adicional',s=>s.ipi||'—'],['Frete CIF / FOB',s=>s.freightType],['Frete FOB',s=>s.freightType==='FOB'?s.freight||'—':'0'],['Outras despesas',s=>s.extra||'—'],['Total final',(_,i)=>sums[i].final===null?'Incompleto':qMoney(sums[i].final)],['Pagamento',s=>s.payment||'—'],['Entrega',s=>s.delivery||'—'],['Observações',s=>s.notes||'—']].map(([label,fn])=>`<tr><td>${label}</td>${QUOTE.suppliers.map((s,i)=>`<td>${qEsc(fn(s,i))}</td>`).join('')}</tr>`).join('');const map=`<h2>Mapa comparativo · Pharmabag</h2><p>SC ${qEsc(qScList())} · PC ${qEsc(QUOTE.pcNumber||'a informar')} · Comprador ${qEsc(QUOTE.buyer)}</p><p><strong>Fornecedor escolhido:</strong> ${qEsc(QUOTE.suppliers[+QUOTE.chosenSupplier]?.name||'a definir')} · <strong>Justificativa:</strong> ${qEsc(QUOTE.choiceReason||'a registrar')}</p><table><tr><th>Último preço</th><th>SC / item</th><th>Descrição</th><th>Qtd / UM</th>${names.map(x=>'<th>'+x+'<br>Unit. / total</th>').join('')}<th>IPI e ressalvas</th></tr>${items}</table><table><tr><th>Condição</th>${names.map(x=>'<th>'+x+'</th>').join('')}</tr>${terms}</table><p>Anexar ao pedido de compras para compliance. Conferir propostas e condições antes da escolha.</p>`;let html=mode==='quote'?quoteEmailHtml():mode==='both'?quoteEmailHtml()+'<div style="page-break-before:always"></div>'+map:map;const frame=document.createElement('iframe');frame.style.position='fixed';frame.style.width='0';frame.style.height='0';frame.style.border='0';document.body.append(frame);const doc=frame.contentDocument;doc.open();doc.write('<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A3 landscape;margin:12mm}body{font:11px Arial;color:#253b50}table{border-collapse:collapse;width:100%;margin:10px 0}th,td{border:1px solid #d2e0e9;padding:5px;vertical-align:top}th{background:#dcebf7;color:#193855;text-align:left}tr{break-inside:avoid}h2{color:#193855}</style></head><body>'+html+'</body></html>');doc.close();frame.contentWindow.onafterprint=()=>frame.remove();setTimeout(()=>frame.contentWindow.print(),300);setTimeout(()=>frame.remove(),60000)}
async function finishQuote(){if(!QUOTE.pcNumber.trim())return toast('Informe o número do PC antes de finalizar.','err');if(!QUOTE.chosenSupplier&&QUOTE.chosenSupplier!==0)return toast('Escolha um fornecedor.','err');qEvent('processo_finalizado','PC '+QUOTE.pcNumber);QUOTE.status='Finalizado';QUOTE.finishedAt=new Date().toISOString();QUOTE.updatedAt=QUOTE.finishedAt;quoteDirty=true;clearTimeout(quoteTimer);await saveQuote();if(!quoteDirty)printQuote('both')}
